### ISSUE TITLE
建議補全字體貢獻者

### ISSUE THREAD

**Issue by jisbig5** [MoonlitOwen/ChocolateSans#1]
感謝宇文滿月的辛苦修改 我是原作者本人  這個字體最大的貢獻者是  @Steve-Yuu（Y式書作者） @GuiWonder(尚古黑體作者) 我只是把他們繪製的字體 整合在一起 請加註他們 感謝

**Comment by jisbig5** [comment]
還有 @ChiuMing-Neko(秋空黑體作者)也是最大貢獻者

**Comment by MoonlitOwen** [comment]
Done
